name: "basic_qc_filter"
namespace: "methods_qc_filter"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    label: "Aggregated Counts"
    summary: "Unprocessed raw counts after aggregation of transcripts to cells"
    description: "This file contains the raw counts after aggregating transcripts\
      \ to cells.\n"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw aggregated counts"
          required: true
        obs:
        - type: "string"
          name: "cell_id"
          description: "Unique identifier for the cell (from assignment step)"
          required: true
        - type: "string"
          name: "centroid_x"
          description: "X coordinate of the cell"
          required: true
        - type: "string"
          name: "centroid_y"
          description: "Y coordinate of the cell"
          required: true
        - type: "string"
          name: "centroid_z"
          description: "Z coordinate of the cell"
          required: false
        - type: "string"
          name: "n_counts"
          description: "Number of counts in the cell"
          required: true
        - type: "string"
          name: "n_genes"
          description: "Number of genes in the cell"
          required: true
        var:
        - type: "string"
          name: "gene_name"
          description: "Name of the gene"
          required: true
        - type: "string"
          name: "n_counts"
          description: "Number of counts of the gene"
          required: true
        - type: "string"
          name: "n_cells"
          description: "Number of cells expressing the gene"
          required: true
    example:
    - "resources_test/task_ist_preprocessing/mouse_brain_combined/spatial_aggregated_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "QC Columns"
    summary: "QC columns for spatial data"
    description: "This file contains the QC-filter column for spatial data.\n"
    info:
      format:
        type: "h5ad"
        obs:
        - type: "string"
          name: "passed_QC"
          description: "Whether the cell passed the quality control"
          required: true
    example:
    - "resources_test/task_ist_preprocessing/mouse_brain_combined/spatial_qc_col.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--min_counts"
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "double"
    name: "--min_cell_percentage"
    info: null
    default:
    - 0.8
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
label: "Basic QC Filter"
summary: "Get cell filter based on counts per cell."
description: "Get cell filter based on counts per cell. A fixed percentage of cells\
  \ is beeing kept even if they don't pass the QC."
test_resources:
- type: "file"
  path: "resources_test/task_ist_preprocessing/mouse_brain_combined"
  dest: "resources_test/task_ist_preprocessing/mouse_brain_combined"
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "python_script"
  path: "check_config.py"
  is_executable: true
info:
  type: "method"
  subtype: "method_qc_filter"
  type_info:
    label: "QC Filter"
    summary: "Filtering cells based on QC metrics"
    description: "A QC filter method filters cells based on QC metrics."
status: "enabled"
scope:
  image: "public"
  target: "public"
repositories:
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "build/main"
- type: "github"
  name: "datasets"
  repo: "openproblems-bio/datasets"
  tag: "build/main"
license: "MIT"
references:
  doi:
  - "10.1101/2023.02.13.528102"
links:
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
  docker_registry: "ghcr.io"
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "lowcpu"
    - "lowmem"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    pypi:
    - "squidpy"
    - "rasterio"
    github:
    - "theislab/txsim@dev"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
build_info:
  config: "src/methods_qc_filter/basic_qc_filter/config.vsh.yaml"
  runner: "executable"
  engine: "docker|native"
  output: "target/executable/methods_qc_filter/basic_qc_filter"
  executable: "target/executable/methods_qc_filter/basic_qc_filter/basic_qc_filter"
  viash_version: "0.9.4"
  git_commit: "cb66f69121ddb36cba34ced479c9430d9b2b50b8"
  git_remote: "https://github.com/openproblems-bio/task_ist_preprocessing"
package_config:
  name: "task_ist_preprocessing"
  version: "build_main"
  label: "iST Preprocessing"
  summary: "Benchmarking approaches for preprocessing imaging-based spatial transcriptomics"
  description: "Provide a clear and concise description of your task, detailing the\
    \ specific problem it aims\nto solve. Outline the input data types, the expected\
    \ output, and any assumptions or constraints.\nBe sure to explain any terminology\
    \ or concepts that are essential for understanding the task.\n\nExplain the motivation\
    \ behind your proposed task. Describe the biological or computational\nproblem\
    \ you aim to address and why it's important. Discuss the current state of research\
    \ in\nthis area and any gaps or challenges that your task could help address.\
    \ This section\nshould convince readers of the significance and relevance of your\
    \ task.\n"
  info:
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/2023_10x_mouse_brain_xenium_rep1/"
      dest: "resources_test/common/2023_10x_mouse_brain_xenium_rep1/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/2023_yao_mouse_brain_scrnaseq_10xv2/"
      dest: "resources_test/common/2023_yao_mouse_brain_scrnaseq_10xv2/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_ist_preprocessing/"
      dest: "resources_test/task_ist_preprocessing"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
  - type: "github"
    name: "datasets"
    repo: "openproblems-bio/datasets"
    tag: "build/main"
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Louis Kümmerle"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "LouisK92"
      orcid: "0000-0002-9193-1243"
  - name: "Malte D. Luecken"
    roles:
    - "author"
    info:
      github: "LuckyMD"
      orcid: "0000-0001-7464-7921"
  - name: "Daniel Strobl"
    roles:
    - "author"
    info:
      github: "danielStrobl"
      orcid: "0000-0002-5516-7057"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  keywords:
  - "spatial transcriptomics"
  - "imaging-based spatial transcriptomics"
  - "preprocessing"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_ist_preprocessing/issues"
