name: process_zuani_human_nsclc_sc
namespace: datasets/workflows

argument_groups:
  #- name: Inputs
  #  arguments:
  #    - type: file
  #      name: --input
  #      description: Path to the dataset
  #      required: true
  #      example: "ftp://anonymous@ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/526/E-MTAB-13526/Files/10X_Lung_Tumour_Annotated_v2.h5ad"
  - name: Caching settings
    arguments:
      - type: boolean
        name: --keep_files
        required: false
        description: Whether to remove the downloaded files after processing.
        default: false
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: false
        default: "2024Zuani_human_nsclc_sc" 
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: false
        default: "2024Zuani_human_nsclc_sc" 
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
        default: "https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13526" 
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
        default: "https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13526" 
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
        default: "Single cell RNA sequencing atlas of non-small cell lung cancer (NSCLC)" 
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
        default: "We performed single cell RNA sequencing (scRNA-seq) of NSCLC tumours and matched, adjacent, non-involved lung tissue from 24 patients. The data set is composed of approximately 900,000 cells from two different populations: CD235- (haematopoietic and non-haematopoietic cells depleted of erythrocytes), and CD45+ (all haematopoietic cells)." 
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
        default: "human" 
  - name: Outputs
    arguments:
    - name: "--output"
      __merge__: /src/api/file_common_scrnaseq.yaml
      direction: output
      required: true
      default: "$id/dataset.h5ad"
    - name: "--output_meta"
      direction: "output"
      type: file
      description: "Dataset metadata"
      default: "$id/dataset_meta.yaml"

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: datasets/loaders/zuani_human_nsclc_sc
#  - name: datasets/processors/subsample
#    repository: openproblems
  - name: normalization/log_cp
    repository: datasets
  - name: processors/pca
    repository: datasets
  - name: processors/hvg
    repository: datasets
  - name: processors/knn
    repository: datasets
  - name: utils/extract_uns_metadata
    repository: openproblems

runners:
  - type: nextflow
    directives:
      label: [midcpu, midmem, hightime]
