import anndata as ad
import spatialdata as sd
import txsim as tx

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input': 'spatial_norm_counts.h5ad',
  'input_transcripts': 'spatial_assigned.zarr',
  'input_sc': 'sc_norm_counts.h5ad',
  'um_per_pixel': 0.5,
  'output': 'spatial_with_celltypes.h5ad',
  'celltype_key': 'celltype',
}
meta = {
  'name': 'ssam',
}
## VIASH END

# Optional parameter check: For this specific annotation method the par['input_transcripts'] and par['input_sc'] are required
assert par['input_transcripts'] is not None, 'Transcripts input is required for this annotation method.'
assert par['input_sc'] is not None, 'Single cell input is required for this annotation method.'

# Read input
print('Reading input files', flush=True)
adata_sp = ad.read_h5ad(par['input'])
transcripts = sd.SpatialData.read(par['input_transcripts'])['transcripts']
adata_sc = ad.read_h5ad(par['input_sc'])
adata_sp = adata_sp[:,adata_sc.var_names] #TODO: do we want to do this earlier? Maybe not, thinking about transcripts related quality metrics

# Annotate cell types
print('Annotating cell types', flush=True)
adata_sp = tx.preprocessing.run_ssam(
    adata_sp, transcripts.compute(), adata_sc, um_p_px=par['um_per_pixel'], 
    cell_id_col='cell_id', gene_col='feature_name', sc_ct_key=par['celltype_key']
)
adata_sp.obs["cell_type"] = adata_sp.obs["ct_ssam"].astype(str)
#TODO: check if coordinate systems of adata_sp, transcripts and the ssam procedure align and what to do with um_p_px
#      currently ssam most likely outputs bad results since the transcripts are provided in physical space instead of pixel space
#TODO: How to handle 'None_sc' this could annotate spatial cell types as None_sc, these should then be 'None_sp' such that their ignored in the metrics.

# Write output
print('Writing output', flush=True)
adata_sp.write(par['output'])