name: process_dataset
namespace: data_processors

__merge__: /src/api/comp_data_preprocessor.yaml

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: [spatialdata]
  - type: native

runners:
  - type: executable
  - type: nextflow
