import anndata as ad
import txsim as tx

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input': 'spatial_raw_counts.h5ad',
  'input_volume': 'cell_volumes.h5ad',
  'output': 'spatial_norm_counts.h5ad',
}
meta = {
  'name': 'normalise_by_volume',
}
## VIASH END


# Read input
print('Reading input files', flush=True)
adata = ad.read(par['input'])
adata_volume = ad.read(par['input_volume'])
assert adata.obs["cell_id"].astype(int).sort_values().equals(adata_volume.obs["cell_id"].astype(int).sort_values()), "Cell IDs do not match"
adata.obs["volume"] = adata_volume.obs.loc[adata.obs["cell_id"].astype(str), "volume"]

# Normalise by volume
print('Normalising by volume', flush=True)
tx.preprocessing.normalize_by_area(adata, area="volume") #TODO: Add scaling parameter, also as input to the script

# Write output
print('Writing output', flush=True)
adata.write(par['output'])