#!/bin/bash

# Fail loudly: without this, a crash in any sub-step (input.py / script.R /
# output.py) is swallowed and Viash only reports the generic "required output
# file is missing", hiding the real Python/R traceback.
set -eo pipefail

## VIASH START
# The following code has been auto-generated by Viash.
par_input_ist='resources_test/task_ist_preprocessing/mouse_brain_combined/raw_ist.zarr'
par_input_segmentation='resources_test/task_ist_preprocessing/mouse_brain_combined/segmentation.zarr'
par_input_scrnaseq='resources_test/task_ist_preprocessing/mouse_brain_combined/scrnaseq_reference.h5ad'
par_sc_cell_type_key='cell_type'
par_output='resources_test/task_ist_preprocessing/mouse_brain_combined/transcript_assignments.zarr'
par_transcripts_key='transcripts'
par_coordinate_system='global'
meta_name='fastreseg'
meta_functionality_name='fastreseg'
meta_resources_dir='/private/tmp/viash_inject_fastreseg18170326436127140412'
meta_executable='/private/tmp/viash_inject_fastreseg18170326436127140412/fastreseg'
meta_config='/private/tmp/viash_inject_fastreseg18170326436127140412/.config.vsh.yaml'
meta_temp_dir='/var/folders/fq/ymt0vml175s4yvqxzbmlmpz80000gn/T/'
meta_cpus='123'
meta_memory_b='123'
meta_memory_kb='123'
meta_memory_mb='123'
meta_memory_gb='123'
meta_memory_tb='123'
meta_memory_pb='123'
meta_memory_kib='123'
meta_memory_mib='123'
meta_memory_gib='123'
meta_memory_tib='123'
meta_memory_pib='123'

## VIASH END

par_intermediate_dir=$(mktemp -d -p "$(pwd)" tmp-processing-XXXXXXXX)

echo "running FastReseg orchestrator"

# Create intermediate directory
mkdir -p "$par_intermediate_dir"
echo $(date +%T)

# Step 1: Run Python script to reformat input in the first Python environment
python "$meta_resources_dir/input.py" \
  "$par_input_ist" \
  "$par_input_segmentation" \
  "$par_input_scrnaseq" \
  "$par_intermediate_dir/counts.tsv" \
  "$par_intermediate_dir/transcripts.tsv" \
  "$par_intermediate_dir/cell_types.tsv"

head $par_intermediate_dir/cell_types.tsv

# Step 2: RunFastReseg

## running the R script.
## ARG-ORDERING CONTRACT: script.R reads these POSITIONALLY. The first 6 are file paths
## (args[1..6]); the FastReseg tuning knobs are appended AFTER them in this EXACT order and
## must match script.R's args[7..10] and config.vsh.yaml's `arguments:` block:
##   args[7]=molecular_distance_cutoff, args[8]=flagCell_lrtest_cutoff,
##   args[9]=svmClass_score_cutoff,     args[10]=cutoff_spatialMerge.
## A reordering here silently corrupts the run — do not touch one file without the others.
Rscript "$meta_resources_dir/script.R" "$par_intermediate_dir/counts.tsv" \
  "$par_intermediate_dir/transcripts.tsv" \
  "$par_intermediate_dir/cell_types.tsv" \
  "$par_intermediate_dir/cell_ids.csv" \
 "$par_intermediate_dir/gene_names.csv" \
  "$par_intermediate_dir/transcripts_out.csv" \
  "$par_molecular_distance_cutoff" \
  "$par_flagCell_lrtest_cutoff" \
  "$par_svmClass_score_cutoff" \
  "$par_cutoff_spatialMerge"

## python output
python "$meta_resources_dir/output.py" \
  "$par_intermediate_dir/cell_ids.csv" \
  "$par_intermediate_dir/gene_names.csv" \
  "$par_intermediate_dir/transcripts_out.csv" \
  "$par_output"

echo $(date +%T)