import numpy as np
import xarray as xr
import dask
import dask.dataframe as dd
import spatialdata as sd
from spatialdata.models import PointsModel
import txsim as tx
import anndata as ad
import os
import shutil

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_ist': 'resources_test/task_ist_preprocessing/mouse_brain_combined/raw_ist.zarr',
  'input_segmentation': 'resources_test/task_ist_preprocessing/mouse_brain_combined/segmentation.zarr',
  'transcripts_key': 'transcripts',
  'coordinate_system': 'global',
  'output': '../pciSeq_assigned_transcripts.zarr',

  'input_scrnaseq': 'resources_test/task_ist_preprocessing/mouse_brain_combined/scrnaseq_reference.h5ad',
  'sc_cell_type_key': 'cell_type',

  'exclude_genes': None,
  'max_iter': 1000,
  'CellCallTolerance': 0.02,
  'rGene': 20,
  'Inefficiency': 0.2,
  'InsideCellBonus': 2,
  'MisreadDensity': 0.00001,
  'SpotReg': 0.1,
  'nNeighbors': 3,
  'rSpot': 2,
  'save_data': False,
  'dtype': np.float64
}
meta = {
  'name': 'pciSeq_transcript_assignment'
}
## VIASH END

########
# NOTE: Issue https://github.com/acycliq/pciSeq/issues/14 still occurs on some datasets.
#       To tackle this we overwrite the class method with a version that skips the assertion.

def eta_update_no_assert(self):
    """
    Calcs the expected eta
    Implements equation (5) of the Qian paper
    """
    
    #NOTE: assertion removed
    #grand_total = self.cells.background_counts.sum() + self.cells.total_counts.sum()
    #assert round(grand_total) == self.spots.data.shape[0], \
    #  'The sum of the background spots and the total gene counts should be equal to the number of spots' 
        
    classProb = self.cells.classProb
    mu = self.single_cell.mean_expression
    area_factor = self.cells.ini_cell_props['area_factor']
    gamma_bar = self.spots.gamma_bar.compute()
    
    zero_prob = classProb[:, -1]  # probability a cell being a zero expressing cell
    zero_class_counts = self.spots.zero_class_counts(self.spots.gene_id, zero_prob)
    
    # Calcs the sum in the Gamma distribution (equation 5). The zero class
    # is excluded from the sum, hence the arrays in the einsum below stop at :-1
    # Note. I also think we should exclude the "cell" that is meant to keep the
    # misreads, ie exclude the background
    class_total_counts = np.einsum(
        'ck, gk, c, cgk -> g',
        classProb[:, :-1],
        mu.values[:, :-1],
        area_factor,
        gamma_bar[:, :, :-1]
    )
    background_counts = self.cells.background_counts
    alpha = self.config['rGene'] + self.spots.counts_per_gene - background_counts - zero_class_counts
    beta = self.config['rGene'] / self.config['Inefficiency'] + class_total_counts
    
    # Finally, update gene_gamma
    self.genes.calc_eta(alpha, beta)

import pciSeq
pciSeq.src.core.main.VarBayes.eta_upd = eta_update_no_assert

########


# Read input
print('Reading input files', flush=True)
sdata = sd.read_zarr(par['input_ist'])
sdata_segm = sd.read_zarr(par['input_segmentation'])

# Check if coordinate system is available in input data
transcripts_coord_systems = sd.transformations.get_transformation(sdata[par["transcripts_key"]], get_all=True).keys()
assert par['coordinate_system'] in transcripts_coord_systems, f"Coordinate system '{par['coordinate_system']}' not found in input data."
segmentation_coord_systems = sd.transformations.get_transformation(sdata_segm["segmentation"], get_all=True).keys()
assert par['coordinate_system'] in segmentation_coord_systems, f"Coordinate system '{par['coordinate_system']}' not found in input data."

# Transform transcript coordinates to the coordinate system
print('Transforming transcripts coordinates', flush=True)
# Multi-partition parquet files each start with a 0-based index, producing duplicate index
# values in the combined dask DataFrame. sd.transform() internally creates a pd.Series with
# index=transformed.index; when that dask index is computed it triggers an assign expression
# that fails on duplicate/lazy indices. Fix: materialize to pandas and rebuild as a single
# dask partition with a clean RangeIndex before transforming.
# The original sdata[transcripts_key] is left unchanged so lines below remain consistent.
transcripts_input = sdata[par['transcripts_key']]
transcripts_reset = dd.from_pandas(transcripts_input.compute().reset_index(drop=True), npartitions=1)
transcripts_reset.attrs.update(transcripts_input.attrs)
transcripts = sd.transform(transcripts_reset, to_coordinate_system=par['coordinate_system'])

# In case of a translation transformation of the segmentation (e.g. crop of the data), we need to adjust the transcript coordinates
trans = sd.transformations.get_transformation(sdata_segm["segmentation"], get_all=True)[par['coordinate_system']].inverse()
transcripts = sd.transform(transcripts, trans, par['coordinate_system'])

# Assign cell ids to transcripts
print('Assigning transcripts to cell ids', flush=True)
y_coords = transcripts.y.compute().to_numpy()
x_coords = transcripts.x.compute().to_numpy()

#Added for pciSeq
#TODO this will immediately break when the name of the gene isn't feature_name
# Materialize the full transcripts once, in the same row order as the transformed
# x/y coordinates above, so every downstream filter stays positionally aligned.
transcripts_full = sdata[par['transcripts_key']].compute()
transcripts_dataframe = transcripts_full[['feature_name']].copy()
transcripts_dataframe['x'] = x_coords
transcripts_dataframe['y'] = y_coords

#same as before
if isinstance(sdata_segm["segmentation"], xr.DataTree):
    label_image = sdata_segm["segmentation"]["scale0"].image.to_numpy() 
else:
     label_image = sdata_segm["segmentation"].to_numpy()

# There might be spots at the border of the image, pciseq runs into an error if this is the case.
# Build the mask as a positional numpy array from the transformed coords and apply the SAME mask
# to both the pciSeq input and the full transcripts, so pciSeq's per-spot assignments line up
# row-for-row with the transcripts when cell_ids are written back below. (Filtering the original
# multi-partition dask frame by a mask derived from the reset-index transcripts raises an
# "Unalignable boolean Series" IndexingError because the two indices no longer match.)
transcripts_at_border = (x_coords > (label_image.shape[1] - 0.5)) | (y_coords > (label_image.shape[0] - 0.5))
transcripts_dataframe = transcripts_dataframe[~transcripts_at_border]
transcripts_full = transcripts_full[~transcripts_at_border]

# Grab all the pciSeq parameters
opts_keys = [#'exclude_genes',
  'max_iter',
  'CellCallTolerance',
  'rGene',
  'Inefficiency',
  'InsideCellBonus',
  'MisreadDensity',
  'SpotReg',
  'nNeighbors',
  'rSpot',
  'save_data']

opts = {k: par[k] for k in opts_keys}

input_scrnaseq = ad.read_h5ad(par['input_scrnaseq'])
input_scrnaseq.X = input_scrnaseq.layers['counts']

assignments, cell_types = tx.preprocessing.run_pciSeq(
    transcripts_dataframe,
    label_image,
    input_scrnaseq,
    par['sc_cell_type_key'],
    opts
)

#assign transcript -> cell
transformations = sd.transformations.get_transformation(sdata[par['transcripts_key']], get_all=True)
transcripts_pd = transcripts_full.copy()
transcripts_pd["cell_id"] = assignments['cell'].to_numpy()
sdata[par['transcripts_key']] = PointsModel.parse(transcripts_pd, transformations=transformations)

# create new .obs for cells based on the segmentation output (corresponding with the transcripts 'cell_id')
cell_types['type'] = cell_types['type'].replace({'None':'None_sp'})
cell_types.insert(0, 'cell_id', cell_types.index)
cell_types.rename(columns={'type':'cell_type','prob':'cell_type_prob'}, inplace=True)

assert 0 not in cell_types['cell_id'], "Found '0' in cell_id column of assingment output cell matrix"

output_table = ad.AnnData(
      obs=cell_types[['cell_id','cell_type','cell_type_prob']],
    )

# TODO: Also take care of the following cases:
# - segmentation 3D, transcripts 3D
# - segmentation 3D, transcripts 2D
# - segmentation 2D, transcripts 3D

# Subset sdata to transcripts with cell ids

print('Subsetting to transcripts cell id and cell type data', flush=True)
sdata_transcripts_only = sd.SpatialData(
  points={
    "transcripts": sdata[par['transcripts_key']]
  },
  tables={
    "table": output_table
  }
)

print('Write transcripts with cell ids and cell types', flush=True)
if os.path.exists(par["output"]):
  shutil.rmtree(par["output"])
sdata_transcripts_only.write(par['output'])


