import anndata as ad
import os
import shutil

import singlecellexperiment as sce
import singler

## VIASH START
# The following code has been auto-generated by Viash.
par = {
  'input_spatial_normalized_counts': r'resources_test/task_ist_preprocessing/mouse_brain_combined/spatial_normalized_counts.h5ad',
  'input_transcript_assignments': r'resources_test/task_ist_preprocessing/mouse_brain_combined/transcript_assignments.zarr',
  'input_scrnaseq_reference': r'resources_test/task_ist_preprocessing/mouse_brain_combined/scrnaseq_reference.h5ad',
  'celltype_key': r'cell_type',
  'output': r'resources_test/task_ist_preprocessing/mouse_brain_combined/spatial_with_cell_types.h5ad',
  'labels_key': r'cell_labels'
}
meta = {
  'name': r'singleR',
  'functionality_name': r'singleR'
}
dep = {
  
}

## VIASH END
sce_h5ad = sce.read_h5ad(par['input_spatial_normalized_counts'])
adata_sp = ad.read_h5ad(par['input_spatial_normalized_counts'])

sce_ref = sce.read_h5ad(par['input_scrnaseq_reference'])

features = [str(x) for x in sce_h5ad.row_data.row_names]

mat = sce_h5ad.assay("counts") ##example has raw, not sure
mat = mat.sorted_indices() ## magic line to make sure the matrix is in the right format for SingleR

mat_ref = sce_ref.assay("normalized")
mat_ref = mat_ref.sorted_indices() ## magic line to make sure the matrix is in the right format for SingleR

## create the reference from our sc data
built = singler.train_single(ref_data = mat_ref,   
                             ref_labels = sce_ref.get_column_data().column("cell_type"),    
                             ref_features = sce_ref.get_row_names(),    
                             test_features = features,)

## annotate the dataset
output = singler.classify_single(mat, ref_prebuilt=built)

adata_sp.obs["cell_type"] = output['best']

# Write output
print('Writing output', flush=True)
adata_sp.write(par['output'])