__merge__: /src/api/comp_method_transcript_assignment.yaml

name: basic
label: "Basic Transcript Assignment Method"
summary: "Assign transcripts to cells based on a segmentation label image"
description: "The transcripts that are positioned in the same pixel as a cell are assigned to that cell."
links:
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
references:
  doi: "10.1101/2023.02.13.528102"

arguments:
  - name: --transcripts_key
    type: string
    description: The key of the transcripts within the points of the spatial data
    default: transcripts
  - name: --coordinate_system
    type: string
    description: The key of the pixel space coordinate system within the spatial data
    default: global

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    __merge__: 
      - /src/base/setup_spatialdata_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, lowcpu, lowmem ]
