__merge__: /src/api/comp_method_expression_correction.yaml

name: split
label: "SPLIT"
summary: "Correct doublet/misegmented cells using SPLIT"
description: "SPLIT (Spatial Purification of Layered Intracellular Transcripts) is a novel method that integrates snRNA-seq with RCTD deconvolution to enhance signal purity. SPLIT effectively resolves mixed transcriptomic signals, improving background correction and cell-type resolution."
links:
  documentation: "https://github.com/bdsc-tds/SPLIT"
  repository: "https://github.com/bdsc-tds/SPLIT"
references:
  doi: "10.1101/2025.04.23.649965"

arguments:
  - name: --keep_all_cells
    required: false
    direction: input
    type: boolean
    default: false
    description: Whether to keep cells with 0 counts (may cause errors if set to TRUE)

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1
    setup:
      - type: docker
        run: |
          apt-get update
      # - type: r
      #   packages: [fs, rlang, lifecycle]
      - type: r
        bioc: [SingleCellExperiment, anndataR, rhdf5, devtools, scater]
        # bioc: [SpatialExperiment, anndataR, rhdf5, devtools, scater]
      - type: docker
        run: |
          Rscript -e "options(timeout = 600000000); devtools::install_github('dmcable/spacexr', build_vignettes = FALSE); devtools::install_github('bdsc-tds/SPLIT')"

      # SingleCellExperiment part can probably be left out again in the future. It currently fixes a bug described in these issues:
      # https://github.com/drighelli/SpatialExperiment/issues/171
      # https://github.com/satijalab/seurat/issues/9889
      # The reinstall of SingleCellExperiment triggers the correct re-install of SpatialExperiment.

      # Using a large timeout here to reduce failures during GitHub package installation.

  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ hightime, highcpu, highmem ]
