__merge__: /src/api/comp_method_count_aggregation.yaml

name: basic_count_aggregation
label: "Basic Count Aggregation"
summary: "Aggregate transcripts of the cells to a count matrix."
description: "Based on the transcript assignments, aggregate the transcripts of the cells to a count matrix."

links:
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
references:
  doi: "10.1101/2023.02.13.528102"
resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    __merge__: 
      - /src/base/setup_txsim_partial.yaml
      - /src/base/setup_spatialdata_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, lowcpu, lowmem ]
