name: binning
label: "Binning Segmentation"
summary: "Segment the spatial data into equidistant square bins"
description: "The binning method for segmentation serves as a baseline of a poor segmentation"
links:
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
references:
  doi: "10.1101/2023.02.13.528102"
  
__merge__: /src/api/comp_method_segmentation.yaml 

arguments:
  - name: --bin_size
    type: integer
    default: 30

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        pypi: spatialdata
    __merge__: 
      - /src/base/setup_txsim_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, midcpu, midmem ]
