name: binning

__merge__: /src/api/comp_method_segmentation.yaml 

arguments:
  - name: --bin_size
    type: integer
    default: 30


resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: spatialdata
  - type: native

runners:
  - type: executable
  - type: nextflow

test_resources:
  - type: python_script
    path: src/methods_segmentation/binning/test_binning.py
