name: bruker_cosmx
namespace: datasets/loaders

argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --input_raw
        example: "https://smi-public.objects.liquidweb.services/HalfBrain.zip"
        description: "Download file url for the raw data"
      - type: file
        name: --input_flat_files
        example: "https://smi-public.objects.liquidweb.services/Half%20%20Brain%20simple%20%20files%20.zip"
        description: "Download file url for the flat files"
      - type: string
        name: --segmentation_id
        default: ["cell"]
        description: The segmentation identifier
        multiple: true
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
  - name: Outputs
    arguments:
      - name: "--output"
        __merge__: /src/api/file_common_ist.yaml
        direction: output
        required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    __merge__: 
      - /src/base/setup_spatialdata_partial.yaml
    setup:
      - type: python 
        pypi:
          - sopa
      #NOTE: Changeed to sopa releases since work of https://github.com/gustaveroussy/sopa/issues/285 is merged and released
      #- type: python
      #  github: [gustaveroussy/sopa@cosmx_labels]
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu, midtime]
