name: "download_10x_xenium"
namespace: "data_loaders"
version: "build_main"
argument_groups:
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    label: "Common iST Dataset"
    summary: "An unprocessed spatial imaging dataset stored as a zarr file."
    description: "This dataset contains raw images, labels, points, shapes, and tables\
      \ as output by a dataset loader.\n"
    info:
      format:
        type: "spatialdata_zarr"
        variables:
        - name: "replicate_id"
          type: "string"
          description: "The replicate identifier"
          required: true
        - name: "segmentation_id"
          type: "string"
          description: "Custom segmentation identifier"
          required: false
        images:
        - type: "datatree"
          name: "{rep}_image"
          description: "The raw image data"
          required: true
          coordinates:
          - type: "integer"
            name: "c"
            required: true
          - type: "double"
            name: "y"
            required: true
          - type: "double"
            name: "x"
            required: true
        - type: "datatree"
          name: "{rep}_image_3D"
          description: "The raw 3D image data"
          required: false
          coordinates: []
        - type: "datatree"
          name: "{rep}_he_image"
          description: "H&E image data"
          required: false
          coordinates: []
        labels:
        - type: "datatree"
          dtype: "int"
          name: "{rep}_{segm}"
          description: "Custom segmentation of the data"
          required: false
        - type: "datatree"
          dtype: "int"
          name: "{rep}_{segm}_3D"
          description: "Custom segmentation of the 3D data"
          required: false
        points:
        - type: "dataframe"
          name: "{rep}_transcripts"
          description: "Point cloud data of transcripts"
          required: true
          columns:
          - type: "float"
            name: "x"
            required: true
          - type: "float"
            name: "y"
            required: true
          - type: "float"
            name: "z"
            required: true
          - type: "categorical"
            name: "feature_name"
            required: true
          - type: "integer"
            name: "cell_id"
            required: true
          - type: "float"
            name: "qv"
            required: true
          - type: "long"
            name: "transcript_id"
            required: true
          - type: "boolean"
            name: "overlaps_nucleus"
            required: true
        shapes:
        - type: "dataframe"
          name: "{rep}_{segm}_boundaries"
          description: "Cell polygons referring to \"{rep}_{segm}\""
          required: false
          columns:
          - type: "object"
            name: "geometry"
            required: true
        tables:
        - type: "anndata"
          name: "metadata"
          description: "Metadata of spatial dataset"
          required: true
          uns:
          - type: "string"
            name: "dataset_id"
            required: true
          - type: "string"
            name: "dataset_name"
            required: true
          - type: "string"
            name: "dataset_url"
            required: true
          - type: "string"
            name: "dataset_reference"
            required: true
          - type: "string"
            name: "dataset_summary"
            required: true
          - type: "string"
            name: "dataset_description"
            required: true
          - type: "string"
            name: "dataset_organism"
            required: true
          - type: "dictionary"
            name: "variables"
            required: true
            contents:
            - type: "string"
              name: "replicate_id"
              required: true
              multiple: true
            - type: "string"
              name: "segmentation_id"
              required: true
              multiple: true
        - type: "anndata"
          name: "{rep}_{segm}_table"
          description: "Count data referring to \"{rep}_{segm}\""
          required: false
          obs:
          - type: "string"
            name: "cell_id"
            required: true
          var:
          - type: "string"
            name: "gene_ids"
            required: true
          - type: "string"
            name: "feature_types"
            required: true
          obsm:
          - type: "float"
            name: "spatial"
            required: true
        coordinate_systems:
        - type: "string"
          name: "{rep}_global"
          description: "Coordinate system of the replicate"
          required: true
    example:
    - "resources_test/common/2023_10x_mouse_brain_xenium/dataset.zarr"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
- name: "Metadata"
  arguments:
  - type: "string"
    name: "--dataset_id"
    description: "A unique identifier for the dataset"
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_name"
    description: "Nicely formatted name."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_url"
    description: "Link to the original source of the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_reference"
    description: "Bibtex reference of the paper in which the dataset was published."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_summary"
    description: "Short description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_description"
    description: "Long description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--dataset_organism"
    description: "The organism of the sample in the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--input"
    description: "A 10x xenium directory"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--replicate_id"
    description: "The replicate identifier"
    info: null
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--segmentation_id"
    description: "The segmentation identifier"
    info: null
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
info:
  type: "data_loader"
  type_info:
    label: "iST Data Loader"
    summary: "A component to download and store iST data."
    description: "This component downloads data from a resource and stores it as a\
      \ zarr file.\n"
status: "enabled"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "midcpu"
    - "midtime"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    pypi:
    - "spatialdata-io"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
build_info:
  config: "src/data_loaders/download_10x_xenium/config.vsh.yaml"
  runner: "executable"
  engine: "docker|native"
  output: "target/executable/data_loaders/download_10x_xenium"
  executable: "target/executable/data_loaders/download_10x_xenium/download_10x_xenium"
  viash_version: "0.9.0"
  git_commit: "126e8def79dd48aa2605061aec06dd00f689d3e7"
  git_remote: "https://github.com/openproblems-bio/task_ist_preprocessing"
package_config:
  name: "task_ist_preprocessing"
  version: "build_main"
  label: "iST Preprocessing"
  summary: "Benchmarking approaches for preprocessing imaging-based spatial transcriptomics"
  description: "Provide a clear and concise description of your task, detailing the\
    \ specific problem it aims\nto solve. Outline the input data types, the expected\
    \ output, and any assumptions or constraints.\nBe sure to explain any terminology\
    \ or concepts that are essential for understanding the task.\n\nExplain the motivation\
    \ behind your proposed task. Describe the biological or computational \nproblem\
    \ you aim to address and why it's important. Discuss the current state of research\
    \ in\nthis area and any gaps or challenges that your task could help address.\
    \ This section \nshould convince readers of the significance and relevance of\
    \ your task.\n"
  info:
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  repositories:
  - type: "github"
    name: "openproblems-v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "John Doe"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "johndoe"
      orcid: "0000-0000-0000-0000"
      email: "john@doe.me"
      twitter: "johndoe"
      linkedin: "johndoe"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.21203/rs.3.rs-4181617/v1"
  links:
    repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_ist_preprocessing/issues"
