#!/bin/bash

repository="openproblems-bio/core"
version="ebe1ecdf2fe01f5a5eb918e05b8d62087aa1e893"
component="project/create_task_readme"

cache_dir="$HOME/.cache/openproblems/repos/$repository"
executable_path="viash/core/target/executable/${component}/$(basename ${component})"

function get_repository {
  if [ ! -d "$cache_dir" ]; then
    mkdir -p "$cache_dir"
    git clone https://github.com/${repository}.git "$cache_dir" > /dev/null
  fi
}

function update_repository {
  (cd "$cache_dir" && \
    git fetch > /dev/null 2>&1 && \
    git checkout "$version" > /dev/null 2>&1 && \
    git pull > /dev/null 2>&1)
}

get_repository
update_repository

# run the executable
"${cache_dir}/${executable_path}" $@
