name: bidcell
label: "BIDCell Segmentation"
summary: "Cell segmentation using BIDCell deep learning approach"
description: "BIDCell is a deep learning method for cell segmentation in spatial transcriptomics data that uses both morphology and transcript information."
links:
  documentation: "https://github.com/SydneyBioX/BIDCell"
  repository: "https://github.com/SydneyBioX/BIDCell"
references:
  doi: "10.1038/s41467-023-44560-w"

__merge__: /src/api/comp_method_segmentation.yaml

arguments:
  - name: --single_cell_ref
    type: file
    description: "Path to single-cell reference data in H5AD format for marker gene identification"
    required: false
    default: "resources_test/common/2023_yao_mouse_brain_scrnaseq_10xv2/dataset.h5ad"
  - name: --max_overlaps_pos
    type: integer
    default: 4
    description: "Maximum number of cell types that can share a positive marker"
  - name: --max_overlaps_neg
    type: integer
    default: 15
    description: "Maximum number of cell types that can share a negative marker"
  - name: --model_epochs
    type: integer
    default: 10
    description: "Number of training epochs for BIDCell model"
  - name: --min_cell_size
    type: integer
    default: 15
    description: "Minimum cell size in pixels"

resources:
  - type: python_script
    path: script.py

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, lowcpu, highmem, gpu ]

engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        pypi: "numpy<2.0"
      - type: python
        pypi: "imgaug<0.4.1"
      - type: python
        pypi: spatialdata
      - type: python
        pypi: scanpy
      - type: python
        pypi: tifffile
      - type: python
        pypi: opencv-python
      - type: python
        pypi: natsort
      - type: python
        pypi: bidcell
      - type: python
        pypi: dask[dataframe]
      - type: python
        pypi: spatialdata-plot
      - type: python
        pypi: pyyaml
      - type: python
        pypi: scikit-image
      - type: python
        pypi: torch
      - type: python
        pypi: torchvision
  - type: native
