name: bidcell
label: "BIDCell Segmentation"
summary: "Cell segmentation using BIDCell deep learning approach"
description: "BIDCell is a deep learning method for cell segmentation in spatial transcriptomics data that uses both morphology and transcript information."
links:
  documentation: "https://github.com/SydneyBioX/BIDCell"
  repository: "https://github.com/SydneyBioX/BIDCell"
references:
  doi: "10.1038/s41467-023-44560-w"

__merge__: /src/api/comp_method_segmentation.yaml

arguments:
  - name: --input_scrnaseq_reference
    __merge__: /src/api/file_scrnaseq_reference.yaml
    required: false
    direction: input
  - name: --max_overlaps_pos
    type: integer
    default: 4
    description: "Maximum number of cell types that can share a positive marker"
  - name: --max_overlaps_neg
    type: integer
    default: 15
    description: "Maximum number of cell types that can share a negative marker"
  - name: --model_epochs
    type: integer
    default: 10
    description: "Number of training epochs for BIDCell model"
  - name: --min_cell_size
    type: integer
    default: 15
    description: "Minimum cell size in pixels"

resources:
  - type: python_script
    path: script.py

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, lowcpu, highmem, gpu ]

engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: apt
        packages:
          - libgl1-mesa-dri
          - libglib2.0-0
          - libsm6
          - libxext6
          - libfontconfig1
          - libxrender1
          - build-essential
          - git
      - type: python
        pip: --force-reinstall numpy==1.24.4 scipy==1.11.1 scikit-image==0.21.0
      - type: python
        pypi: tifffile==2023.7.18
      - type: python
        pypi: natsort==8.4.0
      - type: python
        pypi: opencv-python-headless==4.8.0.76
      - type: python
        pypi: imgaug==0.4.0
      - type: python
        pypi: matplotlib==3.7.2
      - type: python
        pypi: pandas==2.0.3
      - type: python
        pypi: scikit-learn==1.3.0
      - type: python
        pypi: tqdm==4.65.0
      - type: python
        pypi: pyyaml==6.0.1
      - type: python
        pypi: cellpose
      - type: python
        pypi: bidcell
      - type: python
        pypi: spatialdata
      - type: python
        pypi: scanpy
      - type: python
        pypi: dask[dataframe]
      - type: python
        pypi: spatialdata-plot
    __merge__: 
      - /src/base/setup_txsim_partial.yaml
  - type: native

