name: gene_efficiency_correction
namespace: expr_correction_methods

arguments:
  - name: --input
    required: true
    direction: input
    __merge__: /src/api/file_spatial_with_celltypes.yaml
  - name: --input_sc
    required: true
    direction: input
    __merge__: /src/api/file_singlecell.yaml
  - name: --celltype_key
    required: false
    direction: input
    type: string
    default: cell_type
  - name: --output
    required: true
    direction: output
    __merge__: /src/api/file_spatial_corrected.yaml

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: txsim
  - type: native

runners:
  - type: executable
  - type: nextflow
