name: alpha_shapes
namespace: cell_volume_methods

arguments:
  - name: --input
    required: true
    direction: input
    __merge__: /src/api/file_spatialdata_assigned.yaml
  - name: --alpha
    type: double
    description: Alpha parameter for calculating the alpha shape (0.0 refers to the convex hull)
    required: false
    default: 0.0
  - name: --output
    required: true
    direction: output
    __merge__: /src/api/file_spatialdata_assigned.yaml

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: spatialdata, txsim, alphashape, descartes
  - type: native

runners:
  - type: executable
  - type: nextflow
