import os
import re
import json
import shutil
import subprocess
from pathlib import Path

import dask
import numpy as np
import pandas as pd
import anndata as ad
import xarray as xr
import torch
import spatialdata as sd
from spatialdata.models import PointsModel

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_ist': 'resources_test/task_ist_preprocessing/mouse_brain_combined/raw_ist.zarr',
  'input_segmentation': 'resources_test/task_ist_preprocessing/mouse_brain_combined/segmentation.zarr',
  'transcripts_key': 'transcripts',
  'coordinate_system': 'global',
  'output': './temp/methods/segger/segger_assigned_transcripts.zarr',
  'n_epochs': 20,
  'prediction_graph_buffer_ratio': 0.05,
  'prediction_mode': 'cell',
}
meta = {
  'name': 'segger',
  'temp_dir': './temp/methods/segger',
  'cpus': 4,
}
## VIASH END

# The Nextflow/k8s GPU task hands us an EMPTY CUDA_VISIBLE_DEVICES. An empty (or
# whitespace) value masks every GPU from the CUDA *driver* API, so cudf/cuspatial and
# numba enumerate zero devices and segger dies deep in tiling with
# "cudaErrorNoDevice: no CUDA-capable device is detected" / numba's
# "IndexError: list index out of range" (self.gpus[devnum] on an empty device list).
# torch's is_available() is NVML-based and ignores CVD, so the gate below still passes
# and the failure only surfaces inside the `segger segment` subprocess. Drop an empty
# value so the allocated device (exposed via NVIDIA_VISIBLE_DEVICES) is visible again;
# run_segger's os.environ.copy() then inherits the fix for the subprocess.
if os.environ.get("CUDA_VISIBLE_DEVICES", "x").strip() == "":
    print(
        "CUDA_VISIBLE_DEVICES was empty; unsetting so the allocated GPU is visible "
        "to cudf/numba (torch's NVML check hides this).",
        flush=True,
    )
    del os.environ["CUDA_VISIBLE_DEVICES"]

# segger runs its tiling / GNN training / prediction end-to-end on the GPU
# (cudf, cuspatial, torch kernels). Fail fast with a clear message rather than
# deep inside the subprocess when no CUDA device is present.
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE, flush=True)
if DEVICE != "cuda":
    raise RuntimeError(
        "segger requires a CUDA GPU end-to-end and none is available. "
        "Run this component on a GPU-equipped host."
    )

# Working layout for the synthesized Xenium dataset and segger's output.
work_root = Path(meta.get("temp_dir") or "/tmp") / f"segger_{os.getpid()}"
work_root.mkdir(parents=True, exist_ok=True)
XENIUM_DIR = work_root / "xenium_input"
XENIUM_DIR.mkdir(parents=True, exist_ok=True)
SEGGER_OUT_DIR = work_root / "segger_output"

# Load data
print('Reading input files', flush=True)
sdata = sd.read_zarr(par['input_ist'])
sdata_segm = sd.read_zarr(par['input_segmentation'])

transcripts_coord_systems = sd.transformations.get_transformation(sdata[par["transcripts_key"]], get_all=True).keys()
assert par['coordinate_system'] in transcripts_coord_systems, f"Coordinate system '{par['coordinate_system']}' not found in input data."
segmentation_coord_systems = sd.transformations.get_transformation(sdata_segm["segmentation"], get_all=True).keys()
assert par['coordinate_system'] in segmentation_coord_systems, f"Coordinate system '{par['coordinate_system']}' not found in input data."

##########################################
# boundaries.parquet (from segmentation) #
##########################################

# segger consumes a Xenium-layout directory: it links the prior boundary
# polygons (cell/nucleus_boundaries.parquet) to the transcripts by cell_id.
# We derive those boundaries from the provided segmentation, bringing them
# into the transcripts' coordinate system so they align with the transcript
# x/y written below.
print('Computing boundaries from segmentation', flush=True)
boundaries = sd.to_polygons(sdata_segm['segmentation'])[['geometry']]

print('Transforming boundaries to transcripts coordinate system', flush=True)
trans_segm_to_global = sd.transformations.get_transformation(sdata_segm["segmentation"], get_all=True)[par['coordinate_system']]
trans_global_to_transcripts = sd.transformations.get_transformation(sdata[par['transcripts_key']], get_all=True)[par['coordinate_system']].inverse()
trans = sd.transformations.Sequence([trans_segm_to_global, trans_global_to_transcripts])
boundaries = sd.transform(boundaries, trans, par['coordinate_system'])

# Xenium boundary schema: one row per polygon vertex (vertex_x/y float64). cell_id is cast
# to STRING (via int64, so labels render as clean "1"/"2") to match the transcripts.parquet
# cell_id written below: segger joins transcript cell_id -> boundary cell_id to map each cell
# to its polygon, and a str-vs-int mismatch makes every row miss -> all-nan entity_index ->
# "Index has duplicate keys: [nan]" in setup_anndata. Real Xenium v2+ uses string ids in both.
boundaries.index.name = "cell_id"
boundaries_df = boundaries['geometry'].get_coordinates().rename(columns={'x': 'vertex_x', 'y': 'vertex_y'})
boundaries_df = boundaries_df.reset_index()
boundaries_df['cell_id'] = boundaries_df['cell_id'].astype(np.int64).astype(str)
boundaries_df['vertex_x'] = boundaries_df['vertex_x'].astype(np.float64)
boundaries_df['vertex_y'] = boundaries_df['vertex_y'].astype(np.float64)
boundaries_df = boundaries_df[['cell_id', 'vertex_x', 'vertex_y']]
# segger expects both files to exist; we have no cell vs nucleus split, so
# the same polygon set drives whichever `--prediction-mode` selects.
boundaries_df.to_parquet(XENIUM_DIR / "nucleus_boundaries.parquet", index=False)
boundaries_df.to_parquet(XENIUM_DIR / "cell_boundaries.parquet", index=False)
del boundaries, boundaries_df

#######################
# transcripts.parquet #
#######################

# Basic prior assignment: label each transcript with the segmentation cell it
# falls in. Transcript x/y are transformed into the segmentation's pixel space
# only for this lookup; the parquet keeps the transcripts' native coordinates.
print('Transforming transcripts coordinates', flush=True)
# Multi-partition parquet files each start with a 0-based index, producing duplicate index
# values in the combined dask DataFrame. sd.transform() internally creates a pd.Series with
# index=transformed.index; when that dask index is computed it triggers an assign expression
# that fails on duplicate/lazy indices. Fix: materialize to pandas and rebuild as a single
# dask partition with a clean RangeIndex before transforming.
transcripts_input = sdata[par['transcripts_key']]
transcripts_reset = dask.dataframe.from_pandas(transcripts_input.compute().reset_index(drop=True), npartitions=1)
transcripts_reset.attrs.update(transcripts_input.attrs)
transcripts = sd.transform(transcripts_reset, to_coordinate_system=par['coordinate_system'])

# In case of a translation transformation of the segmentation (e.g. crop of the data), we need to adjust the transcript coordinates
trans = sd.transformations.get_transformation(sdata_segm["segmentation"], get_all=True)[par['coordinate_system']].inverse()
transcripts = sd.transform(transcripts, trans, par['coordinate_system'])

print('Assigning transcripts to segmentation cell ids', flush=True)
y_coords = transcripts.y.compute().to_numpy(dtype=np.int64)
x_coords = transcripts.x.compute().to_numpy(dtype=np.int64)
if isinstance(sdata_segm["segmentation"], xr.DataTree):
    label_image = sdata_segm["segmentation"]["scale0"].image.to_numpy()
else:
    label_image = sdata_segm["segmentation"].to_numpy()
# Clip to the label image bounds (transcripts can sit just outside after transform).
n_oob = int(np.count_nonzero((y_coords < 0) | (y_coords >= label_image.shape[0]) | (x_coords < 0) | (x_coords >= label_image.shape[1])))
y_coords = np.clip(y_coords, 0, label_image.shape[0] - 1)
x_coords = np.clip(x_coords, 0, label_image.shape[1] - 1)
print(f"Clamped {n_oob}/{len(x_coords)} transcripts outside the {label_image.shape[0]}x{label_image.shape[1]} label image to its edge", flush=True)
prior_cell_id = label_image[y_coords, x_coords].astype(np.int64)  # 0 == background

# Canonical transcripts frame (native coordinates, clean RangeIndex). Its row
# order matches prior_cell_id and the row_index segger reports back below.
tx_pd = transcripts_reset.compute()
n_tx = len(tx_pd)

if "transcript_id" in tx_pd.columns:
    transcript_id = tx_pd["transcript_id"].to_numpy().astype(np.uint64)
else:
    transcript_id = np.arange(n_tx, dtype=np.uint64)

tx_out = pd.DataFrame({
    "transcript_id": transcript_id,
    "x_location": tx_pd["x"].to_numpy().astype(np.float32),
    "y_location": tx_pd["y"].to_numpy().astype(np.float32),
    "feature_name": tx_pd["feature_name"].astype(str).to_numpy(),
    # segger's Xenium loader keys transcripts to boundaries by cell_id string;
    # background (0) becomes the UNASSIGNED sentinel.
    "cell_id": np.where(prior_cell_id > 0, prior_cell_id.astype(str), "UNASSIGNED"),
    "qv": np.full(n_tx, 40.0, dtype=np.float32),
    "overlaps_nucleus": (prior_cell_id > 0).astype(np.int8),
})
if "z" in tx_pd.columns:
    tx_out.insert(3, "z_location", tx_pd["z"].to_numpy().astype(np.float32))
tx_out.to_parquet(XENIUM_DIR / "transcripts.parquet", index=False)
del transcripts, y_coords, x_coords, label_image

# segger 0.1.0 auto-detects the platform from marker files: its Xenium loader needs an
# `experiment.xenium` JSON and reads only `analysis_sw_version` from it, which selects its
# v1 ("-1") vs v2+ ("UNASSIGNED") loader. We always write the "UNASSIGNED" sentinel above,
# so we need the v2+ loader (version >= 2). Reuse the real version the Xenium dataset
# loader stashed in the metadata table's uns when it is v2+; otherwise (v1 source, missing,
# or a non-Xenium dataset wrapped here as Xenium-layout) fall back to a v2+ default.
DEFAULT_SW_VERSION = "xenium-3.0.0"
sw_version = DEFAULT_SW_VERSION
try:
    src_version = sdata.tables["metadata"].uns.get("xenium_analysis_sw_version")
    if src_version and int(str(src_version).split("-")[-1].split(".")[0]) >= 2:
        sw_version = str(src_version)
    elif src_version:
        print(f"Source Xenium version '{src_version}' is <2, but we write the "
              f"UNASSIGNED sentinel; using {sw_version} instead.", flush=True)
except (KeyError, AttributeError, ValueError, IndexError):
    pass
print(f"Writing experiment.xenium with analysis_sw_version={sw_version}", flush=True)
(XENIUM_DIR / "experiment.xenium").write_text(json.dumps({"analysis_sw_version": sw_version}))

################
# Run segger   #
################

SEGGER_OUT_DIR.mkdir(parents=True, exist_ok=True)
base_cmd = [
    "segger", "segment",
    "-i", str(XENIUM_DIR),
    "-o", str(SEGGER_OUT_DIR),
    "--n-epochs", str(par["n_epochs"]),
    "--prediction-graph-buffer-ratio", str(par["prediction_graph_buffer_ratio"]),
    "--prediction-mode", par["prediction_mode"],
]
# cudf's `validate_setup` aborts `import cudf` on hosts without a usable NVIDIA
# driver; segger imports cudf eagerly during tiling, so skip that validation.
env = os.environ.copy()
env.setdefault("RAPIDS_NO_INITIALIZE", "1")
env.setdefault("CUDF_NO_INITIALIZE", "1")
env.setdefault("RMM_NO_INITIALIZE", "1")


def run_segger(node_dim):
    # --node-representation-dim is segger's `in_channels` (== cells_embedding_size):
    # the PCA n_components for the gene/cell embeddings (segger's own default 128).
    cmd = base_cmd + ["--node-representation-dim", str(int(node_dim))]
    print("Running segger:", " ".join(cmd), flush=True)
    # Stream segger's output live AND capture it, so we can recover the max valid
    # embedding dim from the PCA error below without hiding the training logs.
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1, env=env
    )
    captured = []
    for line in proc.stdout:
        print(line, end="", flush=True)
        captured.append(line)
    proc.wait()
    return proc.returncode, "".join(captured)


# segger runs PCA(n_components=node_dim) on a genes x genes correlation matrix in
# setup_anndata. On small panels/crops fewer genes survive segger's internal count
# filters (cells_min_counts etc.) than node_dim, so the PCA raises e.g.
# "n_components=128 must be between 0 and min(n_samples, n_features)=62". The surviving
# gene count depends on segger's own filtering (not cheaply predictable here), but segger
# reports the exact ceiling in that message, so retry once at that dim. On full panels
# (>=node_dim genes survive) this never triggers.
node_dim = int(par["node_representation_dim"])
returncode, seg_out = run_segger(node_dim)
if returncode != 0:
    m = re.search(r"must be between 0 and min\(n_samples, n_features\)=(\d+)", seg_out)
    if m and 0 < int(m.group(1)) < node_dim:
        max_dim = int(m.group(1))
        print(
            f"segger's gene PCA rejected node_representation_dim={node_dim}: only {max_dim} "
            f"genes survived its count filter. Retrying at {max_dim}.",
            flush=True,
        )
        returncode, seg_out = run_segger(max_dim)
    if returncode != 0:
        raise subprocess.CalledProcessError(returncode, base_cmd)

seg_pq = SEGGER_OUT_DIR / "segger_segmentation.parquet"
if not seg_pq.exists():
    raise RuntimeError(f"Expected segger output not found: {seg_pq}")

######################################################
# Map segger assignments back onto the transcripts   #
######################################################

print('Reading segger output', flush=True)
seg = pd.read_parquet(seg_pq)

# Keep only confident assignments. segger 0.1.0 no longer emits a `keep` column;
# a transcript is confidently assigned when its per-gene similarity clears the
# learned threshold (segger applies exactly this `segger_similarity >=
# similarity_threshold` filter when writing its own AnnData). Also drop
# null / "-1" / "UNASSIGNED" / "NONE" cell ids (case-insensitive).
_UNASSIGNED = {"-1", "UNASSIGNED", "NONE", "NAN", ""}
seg_id_str = seg["segger_cell_id"].astype(str).str.strip().str.upper()
keep_mask = (
    (seg["segger_similarity"] >= seg["similarity_threshold"])
    & seg["segger_cell_id"].notna()
    & ~seg_id_str.isin(_UNASSIGNED)
)
seg = seg[keep_mask]
print(f"segger kept {len(seg)} assignments of {n_tx} transcripts", flush=True)

# segger reports row_index into the transcripts.parquet we wrote (i.e. tx_pd
# row order). Factorize the (string) segger_cell_id into contiguous positive
# integers; unassigned transcripts stay 0.
cell_id_per_tx = np.zeros(n_tx, dtype=np.int64)
if len(seg):
    row_idx = seg["row_index"].to_numpy().astype(np.int64)
    codes, _ = pd.factorize(seg["segger_cell_id"].astype(str), sort=True)
    cell_id_per_tx[row_idx] = codes.astype(np.int64) + 1

#############################################
# Build transcript-assignment output object #
#############################################

transformations = sd.transformations.get_transformation(sdata[par['transcripts_key']], get_all=True)
tx_result = tx_pd.copy()
tx_result["cell_id"] = cell_id_per_tx
tx_result["transcript_id"] = transcript_id
transcripts_points = PointsModel.parse(tx_result, transformations=transformations)

# Cell table: unique assigned cell ids (0/background excluded).
unique_cells = np.unique(cell_id_per_tx)
unique_cells = unique_cells[unique_cells != 0]
cell_id_col = pd.Series(unique_cells, name='cell_id', index=unique_cells)
assert 0 not in cell_id_col, "Found '0' in cell_id column of assignment output cell matrix"

sdata_transcripts_only = sd.SpatialData(
    points={
        "transcripts": transcripts_points
    },
    tables={
        "table": ad.AnnData(
            obs=pd.DataFrame(cell_id_col),
        )
    }
)

print('Write transcripts with cell ids', flush=True)
if os.path.exists(par["output"]):
    shutil.rmtree(par["output"])
sdata_transcripts_only.write(par['output'])

# Best-effort cleanup so the worker doesn't accumulate state across runs.
try:
    shutil.rmtree(work_root)
except OSError as e:
    print(f"(non-fatal) cleanup of {work_root} failed: {e}", flush=True)
