__merge__: ../../api/comp_quality_metric.yaml

name: quality_metrics

# Metadata for your component
info:
  metrics:
    - name: proportion_of_assigned_reads
      label: Proportion of Assigned Reads
      summary: "The proportion of assigned reads."
      description: |
        The proportion of assigned reads.
      references:
        doi: "10.1101/2023.02.13.528102"
      min: 0
      max: 1
      maximize: true
    - name: proportion_of_annotated_cells
      label: Proportion of Annotated Cells
      summary: "The proportion of cells that are annotated with cell types."
      description: |
        The proportion of cells that are annotated with cell types.
      references:
        doi: "10.1101/2023.02.13.528102"
      min: 0
      max: 1
      maximize: true
      
resources:
  - type: python_script
    path: script.py
  - path: /src/metrics/quality/quality_metrics.py

engines:
  - type: docker
    image: openproblems/base_python:1
    __merge__: 
      - /src/base/setup_spatialdata_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
