name: "subset_reference"
namespace: "data_processors"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    description: "A h5ad file containing the data to subset."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    description: "The output file to write the subsetted data to."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_cells"
    description: "The number of cells to sample."
    info: null
    default:
    - 500
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--min_n_cells_per_cell_type"
    description: "The minimum number of cells to sample from each cell type (can be\
      \ less if too many cells or too few cells)."
    info: null
    default:
    - 50
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--cell_type_key"
    description: "The key in the obs dataframe that contains the cell type information."
    info: null
    default:
    - "cell_type"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--keep_cell_type_categories"
    description: "Cell type indexes to be selected"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--keep_features"
    description: "A list of genes to keep."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--keep_tissue_categories"
    description: "Subset the data to cells from the given tissue(s) only."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "integer"
    name: "--seed"
    description: "A seed for the subsampling."
    info: null
    default:
    - 0
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
info: null
status: "enabled"
repositories:
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "build/main"
- type: "github"
  name: "core"
  repo: "openproblems-bio/core"
  tag: "build/main"
  path: "viash/core"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    pypi:
    - "anndata"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/data_processors/subset_reference/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/data_processors/subset_reference"
  executable: "target/nextflow/data_processors/subset_reference/main.nf"
  viash_version: "0.9.0"
  git_commit: "55efb39beb0530e566f82cf904dd36e020fd6bca"
  git_remote: "https://github.com/openproblems-bio/task_ist_preprocessing"
package_config:
  name: "task_ist_preprocessing"
  version: "build_main"
  label: "iST Preprocessing"
  summary: "Benchmarking approaches for preprocessing imaging-based spatial transcriptomics"
  description: "Provide a clear and concise description of your task, detailing the\
    \ specific problem it aims\nto solve. Outline the input data types, the expected\
    \ output, and any assumptions or constraints.\nBe sure to explain any terminology\
    \ or concepts that are essential for understanding the task.\n\nExplain the motivation\
    \ behind your proposed task. Describe the biological or computational \nproblem\
    \ you aim to address and why it's important. Discuss the current state of research\
    \ in\nthis area and any gaps or challenges that your task could help address.\
    \ This section \nshould convince readers of the significance and relevance of\
    \ your task.\n"
  info:
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
  - type: "github"
    name: "core"
    repo: "openproblems-bio/core"
    tag: "build/main"
    path: "viash/core"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "John Doe"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "johndoe"
      orcid: "0000-0000-0000-0000"
      email: "john@doe.me"
      twitter: "johndoe"
      linkedin: "johndoe"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.21203/rs.3.rs-4181617/v1"
  links:
    repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_ist_preprocessing/issues"
