name: custom
namespace: segmentation_methods

arguments:
  - name: --input
    required: true
    direction: input
    __merge__: /src/api/file_spatialdata.yaml
  - name: --labels_key
    type: string
    description: The key of the segmentation within the labels of the spatial data
    required: true
  - name: --output
    required: true
    direction: output
    __merge__: /src/api/file_spatialdata_segmented.yaml

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: spatialdata
  - type: native

runners:
  - type: executable
  - type: nextflow
