import spatialdata as sd

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input': 'resources_test/common/2023_10x_mouse_brain_xenium/dataset.zarr',
  'labels_key': 'rep1_cell', # 'rep1_cell_3D', '{rep}_{segm}_{3D}'
  'output': 'label_image.zarr',
}
meta = {
  'name': 'custom'
}
## VIASH END

# Read input
print('Reading input files', flush=True)
sdata = sd.read_zarr(par['input'])

assert par['labels_key'] in sdata.labels, f"Key '{par['labels_key']}' not found in input data."

# Subset sdata to segmentation
print('Subsetting to segmentation data', flush=True)
sdata_segmentation_only = sd.SpatialData.init_from_elements({par['labels_key']: sdata[par['labels_key']]})

# Rename labels key to 'segmentation'
sdata_segmentation_only.labels['segmentation'] = sdata_segmentation_only.labels.pop(par['labels_key'])

# Write output
sdata_segmentation_only.write(par['output'])