__merge__: /src/api/comp_method_normalization.yaml

name: normalize_by_counts
label: "Normalize by Counts"
summary: "Normalize the spatial transcriptomics data by the total counts"
description: "Normalize the spatial transcriptomics data by the total counts"
links:
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
  repository: "https://github.com/scverse/scanpy"
references:
  doi: "10.1186/s13059-017-1382-0"

arguments:
  - name: --target_sum
    type: double

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        pypi: 
          - scanpy
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, lowcpu, lowmem ]