name: basic
namespace: count_aggregation

arguments:
  - name: --input
    required: true
    direction: input
    __merge__: /src/api/file_spatialdata_assigned.yaml
  - name: --output
    required: true
    direction: output
    __merge__: /src/api/file_spatial_raw_counts.yaml

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi: spatialdata, txsim, squidpy, rasterio
  - type: native

runners:
  - type: executable
  - type: nextflow
