name: basic
namespace: count_aggregation

__merge__: /src/api/comp_method_count_aggregation.yaml

label: Basic
summary: Compute the count aggregation of the input data.
description: >
  This method computes the count aggregation of the input data.

links:
  documentation: ...
  repository: ...

references:
  doi: ...

info:
  preferred_normalization: counts

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    __merge__: 
      - /src/base/setup_txsim_partial.yaml
      - /src/base/setup_spatialdata_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
