name: andrews_human_liver_sc
namespace: datasets/loaders

argument_groups:
  - name: Caching settings
    arguments:
      - type: boolean
        name: --keep_files
        required: false
        description: Whether to remove the downloaded files after processing.
        default: false
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: false
        default: "2022Andrews_human_liver_sc"
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: false
        default: "2022Andrews_human_liver_sc"
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
        default: "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE185477"
        # NOTE: We actually use the cell x gene data access from the 2024 study, also by Andrews:
        #       https://doi.org/10.1016/j.jhep.2023.12.023
        #       Data access: https://cellxgene.cziscience.com/collections/0c8a364b-97b5-4cc8-a593-23c38c6f0ac5
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
        default: "https://doi.org/10.1002/hep4.1854"
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: false
        default: "This dataset contains scRNA-seq data from human liver cells."
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: false
        default: "This dataset contains scRNA-seq data from human liver cells. The data has been published in Andrews et al. 2022, and reanalyzed in Andrews et al. 2024 (data accessed via the 2024 cell x gene release)."
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
        default: "Homo sapiens"
  - name: Outputs
    arguments:
    - name: "--output"
      __merge__: /src/api/file_common_scrnaseq.yaml
      direction: output
      required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    __merge__: 
      - /src/base/setup_txsim_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midmem, midcpu, midtime]
