name: "crop_region"
namespace: "data_processors"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    description: "A zarr file containing the data to crop."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    description: "The output file to write the cropped data to."
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--replicate_id"
    description: "The replicate to crop."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "integer"
    name: "--min_x"
    description: "The minimum x coordinate of the region to crop."
    info: null
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "integer"
    name: "--max_x"
    description: "The maximum x coordinate of the region to crop."
    info: null
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "integer"
    name: "--min_y"
    description: "The minimum y coordinate of the region to crop."
    info: null
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "integer"
    name: "--max_y"
    description: "The maximum y coordinate of the region to crop."
    info: null
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
info: null
status: "enabled"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    pypi:
    - "spatialdata"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/data_processors/crop_region/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/executable/data_processors/crop_region"
  executable: "target/executable/data_processors/crop_region/crop_region"
  viash_version: "0.9.0"
  git_commit: "126e8def79dd48aa2605061aec06dd00f689d3e7"
  git_remote: "https://github.com/openproblems-bio/task_ist_preprocessing"
package_config:
  name: "task_ist_preprocessing"
  version: "build_main"
  label: "iST Preprocessing"
  summary: "Benchmarking approaches for preprocessing imaging-based spatial transcriptomics"
  description: "Provide a clear and concise description of your task, detailing the\
    \ specific problem it aims\nto solve. Outline the input data types, the expected\
    \ output, and any assumptions or constraints.\nBe sure to explain any terminology\
    \ or concepts that are essential for understanding the task.\n\nExplain the motivation\
    \ behind your proposed task. Describe the biological or computational \nproblem\
    \ you aim to address and why it's important. Discuss the current state of research\
    \ in\nthis area and any gaps or challenges that your task could help address.\
    \ This section \nshould convince readers of the significance and relevance of\
    \ your task.\n"
  info:
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  repositories:
  - type: "github"
    name: "openproblems-v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "John Doe"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "johndoe"
      orcid: "0000-0000-0000-0000"
      email: "john@doe.me"
      twitter: "johndoe"
      linkedin: "johndoe"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.21203/rs.3.rs-4181617/v1"
  links:
    repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_ist_preprocessing/issues"
