__merge__: /src/api/comp_method_segmentation.yaml

name: custom
label: "Custom Segmentation Method"
summary: "Copy and output a previous custom segmentation that's already in the sdata.zarr"
description: "Copy and output a previous custom segmentation that's already in the sdata.zarr"
links:
  documentation: "https://github.com/openproblems-bio/task_ist_preprocessing"
  repository: "https://github.com/openproblems-bio/task_ist_preprocessing"
references:
  doi: "10.1101/2023.02.13.528102"

arguments:
  - name: --labels_key
    type: string
    description: The key of the segmentation within the labels of the spatial data
    default: cell_labels

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    __merge__: 
      - /src/base/setup_spatialdata_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, lowcpu, lowmem ]