name: custom

__merge__: /src/api/comp_method_segmentation.yaml

arguments:
  - name: --labels_key
    type: string
    description: The key of the segmentation within the labels of the spatial data
    required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    __merge__: 
      - /src/base/setup_spatialdata_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
