name: allen_brain_cell_atlas
namespace: datasets/loaders

argument_groups:
  - name: Inputs
    arguments:
      - type: string
        name: --abca_version
        required: false
        default: "20230630"
        description: The version of the Allen Brain Cell Atlas to download data from.
      - type: string
        name: --regions
        required: false
        description: A list of brain regions to download data for. If not provided, data for all regions will be downloaded.
        multiple: true
        default:
          - CTXsp
          - HPF
          - HY
          - Isocortex-1
          - Isocortex-2
          - Isocortex-3
          - Isocortex-4
          - MB
          - OLF
          - TH
  - name: Caching
    arguments:
      - type: string
        name: --cache_dir
        required: false
        description: Directory to cache the downloaded data.
      - type: string
        name: --output_cache_dir
        required: false
        description: Output directory of the cached data.
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
  - name: Outputs
    arguments:
    - name: "--output"
      __merge__: /src/api/file_common_scrnaseq.yaml
      direction: output
      required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: 
          - git+https://github.com/alleninstitute/abc_atlas_access
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [veryhighmem, midcpu, midtime]
