name: subset_reference
namespace: data_processors

arguments:
  - type: file
    name: --input
    required: true
    description: A h5ad file containing the data to subset.
  - type: file
    name: --output
    required: true
    description: The output file to write the subsetted data to.
    direction: output
  - type: integer
    name: --n_cells
    required: false
    description: The number of cells to sample.
    default: 500
  - type: integer
    name: --min_n_cells_per_cell_type
    required: false
    description: The minimum number of cells to sample from each cell type (can be less if too many cells or too few cells).
    default: 50
  - type: string
    name: --cell_type_key
    required: false
    description: The key in the obs dataframe that contains the cell type information.
    default: cell_type
  - name: "--keep_cell_type_categories"
    type: "string"
    multiple: true
    description: "Cell type indexes to be selected"
    required: false
  - name: "--keep_features"
    type: string
    multiple: true
    description: A list of genes to keep.
    required: false
  - type: string
    name: --keep_tissue_categories
    required: false
    description: Subset the data to cells from the given tissue(s) only.
    multiple: true
  - name: "--seed"
    type: "integer"
    description: "A seed for the subsampling."
    default: 0


resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        pypi:
          - anndata

runners:
  - type: executable
  - type: nextflow

