name: process_travaglini_human_lung_sc
namespace: datasets/workflows

argument_groups:
  - name: Caching settings
    arguments:
      - type: boolean
        name: --keep_files
        required: false
        description: Whether to remove the downloaded files after processing.
        default: false
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: false
        default: "2020Travaglini_human_lung_sc"
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: false
        default: "2020Travaglini_human_lung_sc"
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
        default: "https://cellxgene.cziscience.com/collections/6f6d381a-7701-4781-935c-db10d30de293"
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
        default: "https://doi.org/10.1038/s41586-020-2922-4"
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: false
        default: "This dataset contains scRNA-seq data from human lung cells."
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: false
        default: "This dataset contains scRNA-seq data from human lung cells."
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
        default: "Homo sapiens"
  - name: Outputs
    arguments:
    - name: "--output_dataset"
      __merge__: /src/api/file_common_scrnaseq.yaml
      direction: output
      required: true
      default: "$id/dataset.h5ad"
    - name: "--output_meta"
      direction: "output"
      type: file
      description: "Dataset metadata"
      default: "$id/dataset_meta.yaml"

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: datasets/loaders/travaglini_human_lung_sc
  - name: normalization/log_cp
    repository: datasets
  - name: processors/pca
    repository: datasets
  - name: processors/hvg
    repository: datasets
  - name: processors/knn
    repository: datasets
  - name: utils/extract_uns_metadata
    repository: openproblems

runners:
  - type: nextflow
    directives:
      label: [midcpu, midmem, hightime]
