name: vizgen_merscope
namespace: datasets/loaders

argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --input
        example: "gs://vz-ffpe-showcase/HumanBreastCancerPatient1"
        description: "Path to the directory containing the dataset in the vizgen google cloud bucket"
      - type: string
        name: --segmentation_id
        default: ["cell"]
        description: The segmentation identifier
        multiple: true
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
  - name: Outputs
    arguments:
      - name: "--output"
        __merge__: /src/api/file_common_ist.yaml
        direction: output
        required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    __merge__: 
      - /src/base/setup_spatialdata_partial.yaml
    setup:
      - type: python
        pypi:
          - spatialdata-io
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu, midtime]
