name: lu_human_liver_cancer_sc
namespace: datasets/loaders

argument_groups:
  - name: Caching settings
    arguments:
      - type: boolean
        name: --keep_files
        required: false
        description: Whether to remove the downloaded files after processing.
        default: false
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: false
        default: "2022Lu_human_liver_cancer_sc"
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: false
        default: "2022Lu_human_liver_cancer_sc"
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
        default: "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE149614"
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
        default: "https://doi.org/10.1038/s41467-022-32283-3"
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: false
        default: "This dataset contains scRNA-seq data from human liver cancer cells."
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: false
        default: "This dataset contains scRNA-seq data from human liver cancer cells."
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
        default: "Homo sapiens"
  - name: Outputs
    arguments:
    - name: "--output"
      __merge__: /src/api/file_common_scrnaseq.yaml
      direction: output
      required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1
    __merge__: 
      - /src/base/setup_txsim_partial.yaml
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midmem, midcpu, midtime]
